# docker run -p 127.0.0.1:8080:8080
# -e KC_BOOTSTRAP_ADMIN_USERNAME=admin
# -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin
# quay.io/keycloak/keycloak:26.6.1
# start-dev

# docker compose up -d
# docker compose down -d

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]

volumes:
  keycloak-data:
